import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Iterator;
import java.util.Map;

/**
 * Class that maps a string generated by the {@link AcornParser} to the
 * corresponding {@link NodeType} constant.
 * The constant is then used as parameter when instantiating an {@link ASTNode}.
 * @author Carl Broberg
 */
public class TypeMapper {

    private final ObjectMapper objectMapper = new ObjectMapper();

    /**
     * Build the AST based on the provided JSON
     * @param json is a JSON string outlining the AST
     * @return the root {@link ASTNode}
     * @throws JsonProcessingException is the JSON cannot be parsed.
     */
    public ASTNode buildTree(String json) throws JsonProcessingException {
        JsonNode root = objectMapper.readTree(json);
        return buildNode(root, null);
    }

    /**
     * Recursively constructs an {@link ASTNode} from a JsonNode.
     * @param jsonNode is the current JsonNode.
     * @return an {@link ASTNode}, or {@code null} if the node has no type.
     */
    private ASTNode buildNode(JsonNode jsonNode, NodeType parentType) {
        if(jsonNode == null || !jsonNode.isObject() || !jsonNode.has("type")) {
            return null;
        }
        String type = jsonNode.get("type").asText();
        NodeType nodeType = mapType(type);
        ASTNode node = new ASTNode(nodeType, jsonNode, parentType);
        Iterator<Map.Entry<String, JsonNode>> fields = jsonNode.fields();
        while(fields.hasNext()) {
            JsonNode child = fields.next().getValue();
            if(child.isObject()) {
                ASTNode childNode = buildNode(child, nodeType);
                if(childNode != null) node.addChild(childNode);
            } else if(child.isArray()) {
                for(JsonNode element : child) {
                    ASTNode childNode = buildNode(element, nodeType);
                    if(childNode != null) node.addChild(childNode);
                }
            }
        }
        return node;
    }

    /**
     * Maps a string to a {@link NodeType} enum constant.
     * @param acornType is the {@code type} value generated by Acorn
     * @return a {@link NodeType} variant
     */
    private NodeType mapType(String acornType) {
        return switch(acornType) {
            case "VariableDeclaration" -> NodeType.VARIABLE_DECLARATION;
            case "CallExpression" -> NodeType.CALL_EXPRESSION;
            case "MemberExpression" -> NodeType.MEMBER_EXPRESSION;
            case "FunctionExpression" -> NodeType.FUNCTION_EXPRESSION;
            case "WithStatement" -> NodeType.WITH_STATEMENT;
            case "ImportDeclaration" -> NodeType.IMPORT_DECLARATION;
            case "Identifier" -> NodeType.IDENTIFIER;
            case "MethodDefinition" -> NodeType.METHOD_DEFINITION;
            default -> null;
        };
    }
}
