import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Class that maps a string generated by the {@link AcornParser} to the
 * corresponding {@link NodeType} constant.
 * The constant is then used as parameter when instantiating an {@link ASTNode}.
 * @author Carl Broberg
 */
public class TypeMapper {

    private final ObjectMapper objectMapper = new ObjectMapper();

    /**
     * Build the AST based on the provided JSON
     * @param json is a JSON string outlining the AST
     * @return the root {@link ASTNode}
     * @throws JsonProcessingException is the JSON cannot be parsed.
     */
    public ASTNode buildTree(String json) throws JsonProcessingException {
        JsonNode root = objectMapper.readTree(json);
        return buildNode(root);
    }

    /**
     * Recursively constructs an {@link ASTNode} from a JsonNode.
     * @param jsonNode is the current JsonNode.
     * @return an {@link ASTNode}, or {@code null} if the node has no type.
     */
    private ASTNode buildNode(JsonNode jsonNode) {
        if(jsonNode == null || !jsonNode.has("type")) {
            return null;
        }

        String acornType = jsonNode.get("type").asText();
        String kind = jsonNode.has("kind") ? jsonNode.get("kind").asText() : "";
        String value = jsonNode.has("name") ? jsonNode.get("name").asText() : acornType;

        NodeType nodeType = mapType(acornType, kind);
        ASTNode node = new ASTNode(nodeType, value);

        // The Acorn fields that contain child nodes
        String[] childFields = {"body", "declarations", "init", "id", "params"};

        for(String field : childFields) {
            if(!jsonNode.has(field)) {
                continue;
            }
            JsonNode child = jsonNode.get(field);

            if(child.isArray()) {
                for(JsonNode element : child) {
                    ASTNode childNode = buildNode(element);
                    if(childNode != null) {
                        node.addChild(childNode);
                    }
                }
            } else if(child.isObject()) {
                ASTNode childNode = buildNode(child);
                if(childNode != null) {
                    node.addChild(childNode);
                }
            }
        }
        return node;
    }

    /**
     * Maps a string to a {@link NodeType} enum constant.
     * @param acornType is the {@code type} value generated by Acorn
     * @param kind is the {@code kind} value generated by Acorn
     * @return a {@link NodeType} variant
     */
    private NodeType mapType(String acornType, String kind) {
        // TODO add all acorn types
        return switch(acornType) {
            case "VariableDeclaration" -> switch (kind) {
                case "var"   -> NodeType.VAR_DECLARATION;
                case "let"   -> NodeType.LET_DECLARATION;
                case "const" -> NodeType.CONST_DECLARATION;
                default      -> null;
            };
            case "FunctionDeclaration" -> NodeType.FUNCTION_DECLARATION;
            case "ArrowFunctionExpression" -> NodeType.ARROW_FUNCTION;
            default -> null;
        };
    }
}
