package config;

/**
 * Configurations class for LLM API communication and data storage.
 * @author Carl Broberg
 */
public final class AppConfig {

    /**
     * Avoid instantiation of static class
     */
    private void SnippetCollector() {}

    /**
     * The private API key used for the GPT API
     */
    public static final String GPT_API_KEY = "api-key-placeholder"; //TODO replace with real key

    /**
     * The private API key used for the Claude API
     */
    public static final String CLAUDE_API_KEY = "api-key-placeholder"; //TODO replace with real key

    /**
     * The URL of the GPT API
     */
    public static final String GPT_API_URL = "https://api.openai.com/v1/chat/completions";

    /**
     * The URL of the Claude API
     */
    public static final String CLAUDE_API_URL = "https://api.anthropic.com/v1/messages";

    /**
     * The name of the models being tested
     */
    public static final String GPT_MODEL_NANO = "gpt-5.4-nano-2026-03-17";
    public static final String GPT_MODEL = "gpt-5.4-2026-03-05";
    public static final String CLAUDE_MODEL_HAIKU = "claude-haiku-4-5-20251001";
    public static final String CLAUDE_MODEL_SONNET = "claude-sonnet-4-6";

    /**
     * The location of the JSON file containing prompts used to query the LLMs
     */
    public static final String PROMPTS_BASELINE_JSON = "data/prompts_baseline.json";
    public static final String PROMPTS_RECENCY_JSON = "data/prompts_recency.json";

    /**
     * The location of the JSON file containing code snippets generated by the LLMs
     */
    public static final String SNIPPETS_BASELINE_JSON = "data/snippets_baseline.json";
    public static final String SNIPPETS_RECENCY_JSON = "data/snippets_recency.json";
}
